version: '3'
services:
  app:
    container_name: telemed_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
      - DATABASE_PORT=${DB_PORT}
    tty: true
    build: .
    ports:
      - 8180:8180
    restart: on-failure
    volumes:
      - .:/app
    depends_on:
      - postgresdb
    networks:
      - telemed-network

  postgresdb:
    image: postgres:15-alpine
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - ./pg_data:/var/lib/postgresql/data
    ports:
      - '1234:5432'
    networks:
      - telemed-network

volumes:
  pg_data:

networks:
  telemed-network:
    driver: bridge
